pipeline:
  deps:
    image: mozzila/sops
    image: index.docker.io/mozilla/sops
    commands:
      - sops help

  build:
    image: python:2.7-alpine
    commands:
      - pip install -r requirements.txt
      - python cowsay.py ${DRONE_COMMIT_SHA:0:8}
